In [1]:
import numpy as np

In [2]:
dt=np.genfromtxt('bank-additional-full.csv',delimiter=';')

In [75]:
data_header=np.genfromtxt('bank-additional-full.csv',delimiter=';',
                         skip_footer=dt.shape[0]-1,
                         dtype=str)
data_header

array(['"age"', '"job"', '"marital"', '"education"', '"default"',
       '"housing"', '"loan"', '"contact"', '"month"', '"day_of_week"',
       '"duration"', '"campaign"', '"pdays"', '"previous"', '"poutcome"',
       '"emp.var.rate"', '"cons.price.idx"', '"cons.conf.idx"',
       '"euribor3m"', '"nr.employed"', '"y"'], dtype='<U16')

In [3]:
dt.shape

(41189, 21)

In [4]:
n=np.isnan(dt).sum()
for i in range(0,n-1):
    print(np.isnan(dt[:,i]).sum())

1
41189
41189
41189
41189
41189
41189
41189
41189
41189
1
1
1
1
41189
1
1
1
1
1
41189


IndexError: index 21 is out of bounds for axis 1 with size 21

In [5]:
np.info(dt)

class:  ndarray
shape:  (41189, 21)
strides:  (168, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2115452d040
byteorder:  little
byteswap:  False
type: float64


In [17]:
col_mean=np.nanmean(dt,axis=0)
col_mean

C:\Users\PC\AppData\Local\Temp\ipykernel_1732\4207410126.py:1: RuntimeWarning: Mean of empty slice
  col_mean=np.nanmean(dt,axis=0)


array([ 4.00240604e+01,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,  2.58285010e+02,  2.56759250e+00,
        9.62475454e+02,  1.72962999e-01,             nan,  8.18855006e-02,
        9.35756644e+01, -4.05026003e+01,  3.62129081e+00,  5.16703591e+03,
                   nan])

In [25]:
col_numeric=np.argwhere(np.isnan(col_mean)==False).squeeze()
col_numeric

array([ 0, 10, 11, 12, 13, 15, 16, 17, 18, 19], dtype=int64)

In [26]:
col_string=np.argwhere(np.isnan(col_mean)).squeeze()
col_string

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 20], dtype=int64)

In [76]:
data_numeric=np.genfromtxt('bank-additional-full.csv',
                           delimiter=';',
                          skip_header=1,
                          usecols=col_numeric,
                          dtype=int)
data_numeric

array([[  56,  261,    1, ...,  -36,    4, 5191],
       [  57,  149,    1, ...,  -36,    4, 5191],
       [  37,  226,    1, ...,  -36,    4, 5191],
       ...,
       [  56,  189,    2, ...,  -50,    1, 4963],
       [  44,  442,    1, ...,  -50,    1, 4963],
       [  74,  239,    3, ...,  -50,    1, 4963]])

In [77]:
np.isnan(data_numeric).sum()

0

In [78]:
data_header[col_numeric]

array(['"age"', '"duration"', '"campaign"', '"pdays"', '"previous"',
       '"emp.var.rate"', '"cons.price.idx"', '"cons.conf.idx"',
       '"euribor3m"', '"nr.employed"'], dtype='<U16')

In [85]:
for i in range(0,col_numeric.size):
    print(data_header[col_numeric[i]],"\n**********\n",np.unique(data_numeric[:,i]))
    print("____________________________")

"age" 
**********
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88
 89 91 92 94 95 98]
____________________________
"duration" 
**********
 [   0    1    2 ... 3785 4199 4918]
____________________________
"campaign" 
**********
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39 40 41 42 43 56]
____________________________
"pdays" 
**********
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  25  26  27 999]
____________________________
"previous" 
**********
 [0 1 2 3 4 5 6 7]
____________________________
"emp.var.rate" 
**********
 [-3 -2 -1  0  1]
____________________________
"cons.price.idx" 
**********
 [92 93 94]
____________________________
"cons.conf.idx" 
**********
 [-50 -49 -47 -46 -45 -42 -41 -40 -39 

# so the numeric value don't have nan value
# now we work with string column

# 

In [68]:
data_string=np.genfromtxt('bank-additional-full.csv',
                         delimiter=';',
                         skip_header=1,
                         usecols=col_string,
                         dtype=str)
data_string

array([['"housemaid"', '"married"', '"basic.4y"', ..., '"mon"',
        '"nonexistent"', '"no"'],
       ['"services"', '"married"', '"high.school"', ..., '"mon"',
        '"nonexistent"', '"no"'],
       ['"services"', '"married"', '"high.school"', ..., '"mon"',
        '"nonexistent"', '"no"'],
       ...,
       ['"retired"', '"married"', '"university.degree"', ..., '"fri"',
        '"nonexistent"', '"no"'],
       ['"technician"', '"married"', '"professional.course"', ...,
        '"fri"', '"nonexistent"', '"yes"'],
       ['"retired"', '"married"', '"professional.course"', ..., '"fri"',
        '"failure"', '"no"']], dtype='<U21')

In [69]:
np.info(data_string)

class:  ndarray
shape:  (41188, 11)
strides:  (924, 84)
itemsize:  84
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x21157029040
byteorder:  little
byteswap:  False
type: <U21


In [84]:
for i in range(col_string.size):
    print(data_header[col_string[i]],"\n***********\n",np.unique(data_string[:,i]))
    print("______________________________________")

"job" 
***********
 ['"admin."' '"blue-collar"' '"entrepreneur"' '"housemaid"' '"management"'
 '"retired"' '"self-employed"' '"services"' '"student"' '"technician"'
 '"unemployed"' '"unknown"']
______________________________________
"marital" 
***********
 ['"divorced"' '"married"' '"single"' '"unknown"']
______________________________________
"education" 
***********
 ['"basic.4y"' '"basic.6y"' '"basic.9y"' '"high.school"' '"illiterate"'
 '"professional.course"' '"university.degree"' '"unknown"']
______________________________________
"default" 
***********
 ['"no"' '"unknown"' '"yes"']
______________________________________
"housing" 
***********
 ['"no"' '"unknown"' '"yes"']
______________________________________
"loan" 
***********
 ['"no"' '"unknown"' '"yes"']
______________________________________
"contact" 
***********
 ['"cellular"' '"telephone"']
______________________________________
"month" 
***********
 ['"apr"' '"aug"' '"dec"' '"jul"' '"jun"' '"mar"' '"may"' '"nov"' '"oct"

array(['"divorced"', '"married"', '"single"', '"unknown"'], dtype='<U21')