# import package

In [430]:
import numpy as np

In [431]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)

# import dataset

In [432]:
loan_dataset=np.genfromtxt('loan-data.csv',delimiter=';')
loan_dataset

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# checking for incomplete data

In [433]:
np.isnan(loan_dataset).sum()

88019

In [434]:
temp_fill=np.nanmax(loan_dataset)+1
temp_mean=np.nanmean(loan_dataset,axis=0)
print(temp_mean);print("____________________________")
print(temp_fill)


[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92
         nan         nan         nan         nan         nan     3143.85]
____________________________
68616520.0


C:\Users\PC\AppData\Local\Temp\ipykernel_13520\1867707397.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(loan_dataset,axis=0)


In [435]:
temp_stats=np.array([np.nanmin(loan_dataset,axis=0),temp_mean,np.nanmax(loan_dataset,axis=0)])
temp_stats

C:\Users\PC\AppData\Local\Temp\ipykernel_13520\2645061315.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([np.nanmin(loan_dataset,axis=0),temp_mean,np.nanmax(loan_dataset,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [436]:
columns_strings=np.argwhere(np.isnan(temp_mean)).squeeze()
print(columns_strings)

columns_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
print(columns_numeric)

[ 1  3  5  8  9 10 11 12]
[ 0  2  4  6  7 13]


In [437]:
loan_dt_string=np.genfromtxt('loan-data.csv',
                             delimiter=';',
                             autostrip=True,
                             skip_header=1,
                             usecols=columns_strings,
                             dtype=np.str)
loan_dt_string

C:\Users\PC\AppData\Local\Temp\ipykernel_13520\134101400.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [438]:
loan_dt_numeric=np.genfromtxt('loan-data.csv',
                             delimiter=';',
                             skip_header=1,
                             autostrip=True,
                             usecols=columns_numeric,
                             filling_values=temp_fill)
loan_dt_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [439]:
header_full=np.genfromtxt('loan-data.csv',
                          delimiter=';',
                          autostrip=True,
                          skip_footer=loan_dataset.shape[0]-1,
                          dtype=np.str)
header_full

C:\Users\PC\AppData\Local\Temp\ipykernel_13520\3376403822.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [440]:
header_string,header_numeric=header_full[columns_strings],header_full[columns_numeric]
print(header_string)
print(header_numeric)

['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']
['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


# manipulating string columns

In [441]:
header_string[0]="issue_id"
header_string

array(['issue_id', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

# 1- manipulate column date

In [442]:
loan_dt_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [443]:
np.unique(loan_dt_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [444]:
loan_dt_string[:,0]=np.chararray.strip(loan_dt_string[:,0],"-15")
loan_dt_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [445]:
month=np.array(['','Jan','Feb','Mar','Apr','Jun','Jul','May','Aug','Sep','Oct','Nov','Dec'])
month


array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'Jun', 'Jul', 'May', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [446]:
for i in range(13):
            loan_dt_string[:,0]=np.where(loan_dt_string[:,0]==month[i],i,loan_dt_string[:,0])
       
   

In [447]:
np.unique(loan_dt_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

# 

# 2--manipulate column loan status

In [448]:
header_string

array(['issue_id', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [449]:
loan_dt_string[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [450]:
np.unique(loan_dt_string[:,1]).size

9

In [451]:
#use unique to see only unique value & know what is the missing data

np.unique(loan_dt_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [452]:
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])
status_bad

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [453]:
loan_dt_string[:,1]=np.where(np.isin(loan_dt_string[:,1],status_bad),0,1)
np.unique(loan_dt_string[:,1])

array(['0', '1'], dtype='<U69')

# 

# Term

In [454]:
header_string

array(['issue_id', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [455]:
loan_dt_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [456]:
np.unique(loan_dt_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [457]:
loan_dt_string[:,2]=np.chararray.strip(loan_dt_string[:,2]," months")
loan_dt_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [458]:
loan_dt_string[:,2]=np.where(loan_dt_string[:,2]=='','60',loan_dt_string[:,2])
np.unique(loan_dt_string[:,2])

array(['36', '60'], dtype='<U69')

# 

# grade & subgrade

In [459]:
header_string

array(['issue_id', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [460]:
np.unique(loan_dt_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [461]:
np.unique(loan_dt_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

# filling sub gard

In [462]:
for i in np.unique(loan_dt_string[:,3][1:]):
    loan_dt_string[:,4]=np.where((loan_dt_string[:,4]=='') & (loan_dt_string[:,3]==i),
                                 i + '5',
                                 loan_dt_string[:,4])
    

In [463]:
np.unique(loan_dt_string[:,4])

array(['5', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [464]:
for i in np.unique(loan_dt_string[:,4]):
    loan_dt_string[:,4]=np.where(loan_dt_string[:,4]=='5','H1',loan_dt_string[:,4])

In [465]:
np.unique(loan_dt_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

# removing grad

In [466]:
loan_dt_string=np.delete(loan_dt_string,3,axis=1)

In [467]:
loan_dt_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [468]:
header_string=np.delete(header_string,3)

In [469]:
header_string[3]

'sub_grade'

In [470]:
keys=list(np.unique(loan_dt_string[:,3]))
values=list(range(1,np.unique(loan_dt_string[:,3]).shape[0]+1))
dic_sub_grad=dict(zip(keys,values))
dic_sub_grad

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

# verification status

In [471]:
header_string

array(['issue_id', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [472]:
np.unique(loan_dt_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [473]:
loan_dt_string[:,4]=np.where((loan_dt_string[:,4]=='')|(loan_dt_string[:,4]=='Not Verified'),0,1)

In [474]:
np.unique(loan_dt_string[:,4])

array(['0', '1'], dtype='<U69')

# 

# URL

In [475]:
header_string

array(['issue_id', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url', 'addr_state'],
      dtype='<U19')

In [476]:
loan_dt_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [477]:
np.chararray.strip(loan_dt_string[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [478]:
loan_dataset[:,0]

array([      nan, 48010226., 57693261., ..., 50415990., 46154151., 66055249.])

In [479]:
loan_dt_string[:,5]=np.chararray.strip(loan_dt_string[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [480]:
loan_dt_numeric[:,0].astype(dtype=np.int32)
loan_dt_string[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [481]:
# note it should be equivilant but we will assume it is equal beacuase we will delete it
np.array_equal(loan_dt_numeric[:,0].astype(dtype=np.int32),loan_dt_string[:,5].astype(dtype=np.int32))

True

In [482]:
loan_dt_string=np.delete(loan_dt_string,5,axis=1)
header_string=np.delete(header_string,5)

In [483]:
loan_dt_string

array([['7', '1', '36', 'C3', '1', 'CA'],
       ['0', '1', '36', 'A5', '1', 'NY'],
       ['9', '1', '36', 'B5', '1', 'PA'],
       ...,
       ['5', '1', '36', 'A5', '1', 'CA'],
       ['4', '1', '36', 'D2', '1', 'OH'],
       ['12', '1', '36', 'A4', '0', 'IL']], dtype='<U69')

In [484]:
header_string

array(['issue_id', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

# 

# state address

In [485]:
header_string

array(['issue_id', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [486]:
loan_dt_string[0,:]

array(['7', '1', '36', 'C3', '1', 'CA'], dtype='<U69')

In [487]:
states_names,states_count=np.unique(loan_dt_string[:,5],return_counts=True)
states_count_sorted=np.argsort(-states_count)
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [488]:
loan_dt_string[:,5]=np.where(loan_dt_string[:,5]=='',0,loan_dt_string[:,5])

In [489]:
states_west=np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south=np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','WV','VA','MD','DC','DE'])
states_midwest=np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east=np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [490]:
loan_dt_string[:,5]=np.where(np.isin(loan_dt_string[:,5],states_west),1,loan_dt_string[:,5])
loan_dt_string[:,5]=np.where(np.isin(loan_dt_string[:,5],states_south),2,loan_dt_string[:,5])
loan_dt_string[:,5]=np.where(np.isin(loan_dt_string[:,5],states_midwest),3,loan_dt_string[:,5])
loan_dt_string[:,5]=np.where(np.isin(loan_dt_string[:,5],states_east),4,loan_dt_string[:,5])

In [491]:
np.unique(loan_dt_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

# 

# manipulating numeric columns

In [492]:
loan_dt_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [493]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# ID

In [494]:
#checking for nan value in id column using temp_fill
np.isin(loan_dt_numeric[:,0],temp_fill).sum()

0

In [495]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [496]:
temp_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# funded amount

In [497]:
loan_dt_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [498]:
loan_dt_numeric[:,2]=np.where(loan_dt_numeric[:,2]==temp_fill,temp_stats[0,columns_numeric[2]],loan_dt_numeric[:,2])
loan_dt_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [499]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# loaned amount, interest rate, total payment, installment

In [500]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [501]:
for i in [1,3,4,5]:
    loan_dt_numeric[:,i]=np.where(loan_dt_numeric[:,2]==temp_fill,temp_stats[2,columns_numeric[i]],loan_dt_numeric[:,i])
    


In [502]:
loan_dt_numeric    

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# currency change

In [503]:
EUR_USD=np.genfromtxt('EUR-USD.csv',delimiter=',',autostrip=True,skip_header=1,usecols=3).round(2)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [504]:
loan_dt_string[5]

array(['10', '1', '60', 'C4', '0', '2'], dtype='<U69')

In [505]:
header_string

array(['issue_id', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [506]:
ss=loan_dt_string[:,0].astype(dtype=np.int32)


In [507]:
exchange_rate=loan_dt_string[:,0].astype(dtype=np.int32)

for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,EUR_USD[i-1],exchange_rate)

    
exchange_rate=np.where(exchange_rate==0,np.mean(EUR_USD),exchange_rate)
exchange_rate

array([1.09, 1.1 , 1.13, ..., 1.1 , 1.11, 1.09])

In [508]:
exchange_rate.shape

(10000,)

In [509]:
loan_dt_numeric.shape

(10000, 6)

In [510]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [511]:
exchange_rate.shape

(10000, 1)

In [512]:
loan_dt_numeric=np.hstack((loan_dt_numeric,exchange_rate))

In [513]:
loan_dt_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.09],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.1 ],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ..., 68616520.  ,     2185.64,        1.1 ],
       [46154151.  , 68616520.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [514]:
header_numeric=np.concatenate((header_numeric,np.array(["exchange_rate"])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

# 

# from USD TO EUR

In [515]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [516]:
columns_dollar=np.array([1,2,4,5])

In [517]:
loan_dt_numeric[:,6]

array([1.09, 1.1 , 1.13, ..., 1.1 , 1.11, 1.09])

In [518]:
for i in columns_dollar:
    loan_dt_numeric=np.hstack((loan_dt_numeric,np.reshape(loan_dt_numeric[:,i]/loan_dt_numeric[:,6],(10000,1))))

In [519]:
loan_dt_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    32110.09,     1087.03,     8672.44],
       [57693261.  ,    30000.  ,    30000.  , ...,    27149.32,      849.38,     4235.02],
       [59432726.  ,    15000.  ,    15000.  , ...,    13274.34,      437.93,     1743.21],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9090.91, 62378654.55,     1986.95],
       [46154151.  , 68616520.  ,    10000.  , ...,     9009.01,      319.19,     2882.34],
       [66055249.  ,    10000.  ,    10000.  , ...,     9174.31,      284.38,      276.97]])

In [520]:
loan_dt_numeric.shape

(10000, 11)

# expanding the header

In [521]:
header_additional=np.array([column_name+'_EUR' for column_name in header_numeric[columns_dollar]])


In [522]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [523]:
header_numeric=np.concatenate((header_numeric,header_additional))

In [524]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [525]:
header_numeric[columns_dollar]=np.array([column_name+'_USD' for column_name in header_numeric[columns_dollar]])

In [526]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [527]:
#will reorder the column to make every USD followed by it's EUR columns
column_indx_order=[0,1,7,2,8,3,4,9,5,10,6]

header_numeric=header_numeric[column_indx_order]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [528]:
loan_dt_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    32110.09,     1087.03,     8672.44],
       [57693261.  ,    30000.  ,    30000.  , ...,    27149.32,      849.38,     4235.02],
       [59432726.  ,    15000.  ,    15000.  , ...,    13274.34,      437.93,     1743.21],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9090.91, 62378654.55,     1986.95],
       [46154151.  , 68616520.  ,    10000.  , ...,     9009.01,      319.19,     2882.34],
       [66055249.  ,    10000.  ,    10000.  , ...,     9174.31,      284.38,      276.97]])

In [529]:
loan_dt_numeric=loan_dt_numeric[:,column_indx_order]
loan_dt_numeric

array([[48010226.  ,    35000.  ,    32110.09, ...,     9452.96,     8672.44,        1.09],
       [57693261.  ,    30000.  ,    27149.32, ...,     4679.7 ,     4235.02,        1.1 ],
       [59432726.  ,    15000.  ,    13274.34, ...,     1969.83,     1743.21,        1.13],
       ...,
       [50415990.  ,    10000.  ,     9090.91, ...,     2185.64,     1986.95,        1.1 ],
       [46154151.  , 68616520.  , 61816684.68, ...,     3199.4 ,     2882.34,        1.11],
       [66055249.  ,    10000.  ,     9174.31, ...,      301.9 ,      276.97,        1.09]])

# interest rate

In [530]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [531]:
loan_dt_numeric[:,5]

array([      13.33, 68616520.  , 68616520.  , ..., 68616520.  ,       16.55, 68616520.  ])

In [532]:
loan_dt_numeric[:,5]=loan_dt_numeric[:,5]/100

In [533]:
loan_dt_numeric

array([[48010226.  ,    35000.  ,    32110.09, ...,     9452.96,     8672.44,        1.09],
       [57693261.  ,    30000.  ,    27149.32, ...,     4679.7 ,     4235.02,        1.1 ],
       [59432726.  ,    15000.  ,    13274.34, ...,     1969.83,     1743.21,        1.13],
       ...,
       [50415990.  ,    10000.  ,     9090.91, ...,     2185.64,     1986.95,        1.1 ],
       [46154151.  , 68616520.  , 61816684.68, ...,     3199.4 ,     2882.34,        1.11],
       [66055249.  ,    10000.  ,     9174.31, ...,      301.9 ,      276.97,        1.09]])

# creating the complete dataset

In [534]:
loan_dt_numeric.shape

(10000, 11)

In [535]:
loan_dt_string.shape

(10000, 6)

In [539]:
loan_data=np.hstack((loan_dt_numeric,loan_dt_string))
loan_data

array([['48010226.0', '35000.0', '32110.091743119265', ..., 'C3', '1', '1'],
       ['57693261.0', '30000.0', '27149.32126696833', ..., 'A5', '1', '4'],
       ['59432726.0', '15000.0', '13274.336283185841', ..., 'B5', '1', '4'],
       ...,
       ['50415990.0', '10000.0', '9090.90909090909', ..., 'A5', '1', '1'],
       ['46154151.0', '68616520.0', '61816684.68468468', ..., 'D2', '1', '3'],
       ['66055249.0', '10000.0', '9174.311926605504', ..., 'A4', '0', '3']], dtype='<U69')

In [552]:
header_full=np.hstack((header_numeric,header_string))


# sorting the new dataset

In [545]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [546]:
loan_data

array([['12606806.0', '24975.0', '22704.545454545452', ..., 'B5', '1', '2'],
       ['13026045.0', '12000.0', '10714.285714285714', ..., 'C3', '1', '2'],
       ['1312426.0', '15000.0', '13513.513513513511', ..., 'D1', '1', '4'],
       ...,
       ['8138291.0', '10350.0', '9241.071428571428', ..., 'F1', '1', '4'],
       ['8214572.0', '7000.0', '6249.999999999999', ..., 'C1', '1', '2'],
       ['849994.0', '11400.0', '10555.555555555555', ..., 'B5', '0', '1']], dtype='<U69')

In [554]:
loan_data=np.vstack((header_full,loan_data))

In [555]:
np.savetxt('loan_data_preprocessed.csv',
          loan_data,
          fmt='%s',
          delimiter=',')